server:
  port: 0

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fi_db
    username: admin_alex
    password: 1231
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect

# Eureka
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8088/eureka/
    register-with-eureka: true
    fetch-registry: true